### ISSUE TITLE
Feature: User can search for games they want to play or have played.

### ISSUE THREAD

**Issue by kttlr** [kyle-kettler/game-queue#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search through a database of all video games to find games they have played or games they want to play.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click on the search bar, enter their search query, and press enter to submit the search. The results will show in a new view. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - 8](https://github.com/kyle-kettler/ajax-project/assets/126023512/c81ffc69-074a-4667-8e9f-1b3b5ad4e5fc)
![X - 2](https://github.com/kyle-kettler/ajax-project/assets/126023512/ed593d3c-ccde-4b60-adff-8ffd9a1bcafd)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add HTML structure of navbar
- [x] Add HTML structure of search results, add `[data-view="search"]`to the parent element.
- [x] Add fonts to project
- [x] Create layout and style classes
- [x] Write an `XMLHTTPRequest` function that searches the RAWG API and returns the results of the search query and creates DOM elements for each result
- [x] Add an event listener to the submit of the search input. The callback function should:
  - [x]  change the view to the search results view
  - [x] clear previous search results
  - [x] Update the page heading to 'Search Results"
  - [x] Call the search function
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
