### ISSUE TITLE
Feature: User can mark games as want to play or played.

### ISSUE THREAD

**Issue by kttlr** [kyle-kettler/game-queue#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to set a game to "want to play" or "played". If they do it will be added to the appropriate list on their dashboard. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user finds a game, there will be two buttons to click "want to play" or "play".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - 5](https://github.com/kyle-kettler/ajax-project/assets/126023512/2d093f4c-7394-48bf-b77f-5f450733a668)
![X - 3](https://github.com/kyle-kettler/ajax-project/assets/126023512/ed7b7646-e102-4e1c-83bc-c4b7d6fc5467)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML structure for `[data-view="game-info"]`
- [x] Write a function to update the game info dom elements.
- [x] Create glow effect behind main image
- [x] Add eventlistener to search results so when a game is clicked, info on that game will be loaded. 
- [x] Create `localstorage` data structure
- [x] Create a function and eventlistener that adds needed elements of the game to local data if the "want to play" or "played" button is clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
