### ISSUE TITLE
Feature: User can rate games they have played.

### ISSUE THREAD

**Issue by kttlr** [kyle-kettler/game-queue#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If the user marks a game as "played" a rate button group will appear. They can then say if they liked or disliked the game. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a game is marked as played, you can leave a thumbs up or thumbs down rating on it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - 6](https://github.com/kyle-kettler/ajax-project/assets/126023512/eeaacef4-1dfa-4298-a925-89734ebf059f)
![X - 4](https://github.com/kyle-kettler/ajax-project/assets/126023512/29cc5cf3-917a-4f61-a73c-1f4e17eee39d)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] If the current game is in local data, then show the rating buttons
- [x] If thumbs up is clicked, update the thumbsUp property of the viewed game to true and set button to active.
- [x] If thumbs down is clicked, update the thumbsDown property of the viewed game to true and set button to active.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
