### ISSUE TITLE
Feature: User can see a list of games they want to play and a list of games played.

### ISSUE THREAD

**Issue by kttlr** [kyle-kettler/game-queue#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

On the primary view of the app the user can see a list of games they want to play and a list of games played.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Once the user has set games to "played" or "want to play" they will show up on the dashboard in separate lists.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![X - 1](https://github.com/kyle-kettler/ajax-project/assets/126023512/0680b77f-fbd4-4369-8545-386058105da4)

![MacBook - 4](https://github.com/kyle-kettler/ajax-project/assets/126023512/728effd4-87e1-47a4-b65a-cfa9fbdd9580)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write HTML and CSS for `[data-view="dashboard"]
- [x] When dashboard is loaded, populate the 'Want to Play' and 'Played' lists with correct items from `localstorage`. 
- [x] add an event listener to the lists that will change the view to `[data-view="game-info"]` on click of the games. Game info will load the game clicked
- [x] The lists of games should only show 16 items, if there is more than 16 the 'See All button will appear. 
- [x] If either 'See All' button is clicked, the view will change to show all games with matching category. 
- [x] If the 'Dashboard' nav link or the logo is clicked, `[data-view="dashboard"]` should be loaded
- [x] Use `@media` to make sure the game images look good at all sizes. 2 columns at small size, 4 columns at medium size, 8 columns at large size.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
