### ISSUE TITLE
Feature: User can create a list of favorite games from games played.

### ISSUE THREAD

**Issue by kttlr** [kyle-kettler/game-queue#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a list of favorite games from games played.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user marks a game as played a star icon will reveal, if they click it the game will be added to their favorites list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - 7](https://github.com/kyle-kettler/ajax-project/assets/126023512/67418d1d-1b9b-4572-bc00-a01ecc72db78)

![X - 8](https://github.com/kyle-kettler/ajax-project/assets/126023512/5aae05bc-f104-4676-b0ee-9d8e3f007538)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add HTML and CSS for star icon
- [x] If the currentGame has been played, show the star icon. 
- [x] If the start icon is clicked, update the `favorite` property of the currentGame.
- [x] Add HTML and CSS for `data-view=favorites`
- [x] When 'favorites' nav item is clicked, show the favorites view with only the games marked as favorite. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
