### ISSUE TITLE
Feature: User can see suggested games when viewing a specific game.

### ISSUE THREAD

**Issue by kttlr** [kyle-kettler/game-queue#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see suggested games when viewing a specific game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is viewing a specific game, three similar games will be shown beneath the current game. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![MacBook - 5](https://github.com/kyle-kettler/ajax-project/assets/126023512/407a43e0-9c58-4bb6-b3ba-dd7361e96b2c)
![X - 3](https://github.com/kyle-kettler/ajax-project/assets/126023512/fab720d7-80ab-4bd8-89a9-8db21fdbbcc5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add HTML and any needed CSS for the Similar Game section.
- [ ] Create a function for query the API for games similar to currentGame
- [ ] Render Similar Games section to Game Info view
- [ ] Whenever `updateGameInfo()` is called make sure to update the similar games to the current game. 
- [ ] Add eventlistener to the similar games so that they can be clicked on and more info is seen about them. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by kttlr** [comment]
This feature needs to be scrapped because the needed endpoint of the API is only available for business-level customers.
